// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transit_fetch.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "transit_fetch.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace valhalla {
namespace mjolnir {

void protobuf_ShutdownFile_transit_5ffetch_2eproto() {
  delete Transit_Fetch::default_instance_;
  delete Transit_Fetch_Stop::default_instance_;
  delete Transit_Fetch_StopPair::default_instance_;
  delete Transit_Fetch_Route::default_instance_;
  delete Transit_Fetch_Shape::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_transit_5ffetch_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_transit_5ffetch_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  Transit_Fetch::default_instance_ = new Transit_Fetch();
  Transit_Fetch_Stop::default_instance_ = new Transit_Fetch_Stop();
  Transit_Fetch_StopPair::default_instance_ = new Transit_Fetch_StopPair();
  Transit_Fetch_Route::default_instance_ = new Transit_Fetch_Route();
  Transit_Fetch_Shape::default_instance_ = new Transit_Fetch_Shape();
  Transit_Fetch::default_instance_->InitAsDefaultInstance();
  Transit_Fetch_Stop::default_instance_->InitAsDefaultInstance();
  Transit_Fetch_StopPair::default_instance_->InitAsDefaultInstance();
  Transit_Fetch_Route::default_instance_->InitAsDefaultInstance();
  Transit_Fetch_Shape::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_transit_5ffetch_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_transit_5ffetch_2eproto_once_);
void protobuf_AddDesc_transit_5ffetch_2eproto() {
  ::google::protobuf::::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_transit_5ffetch_2eproto_once_,
                 &protobuf_AddDesc_transit_5ffetch_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_transit_5ffetch_2eproto {
  StaticDescriptorInitializer_transit_5ffetch_2eproto() {
    protobuf_AddDesc_transit_5ffetch_2eproto();
  }
} static_descriptor_initializer_transit_5ffetch_2eproto_;
#endif

// ===================================================================

bool Transit_Fetch_VehicleType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const Transit_Fetch_VehicleType Transit_Fetch::kTram;
const Transit_Fetch_VehicleType Transit_Fetch::kMetro;
const Transit_Fetch_VehicleType Transit_Fetch::kRail;
const Transit_Fetch_VehicleType Transit_Fetch::kBus;
const Transit_Fetch_VehicleType Transit_Fetch::kFerry;
const Transit_Fetch_VehicleType Transit_Fetch::kCableCar;
const Transit_Fetch_VehicleType Transit_Fetch::kGondola;
const Transit_Fetch_VehicleType Transit_Fetch::kFunicular;
const Transit_Fetch_VehicleType Transit_Fetch::VehicleType_MIN;
const Transit_Fetch_VehicleType Transit_Fetch::VehicleType_MAX;
const int Transit_Fetch::VehicleType_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int Transit_Fetch_Stop::kLonFieldNumber;
const int Transit_Fetch_Stop::kLatFieldNumber;
const int Transit_Fetch_Stop::kGraphidFieldNumber;
const int Transit_Fetch_Stop::kNameFieldNumber;
const int Transit_Fetch_Stop::kOnestopIdFieldNumber;
const int Transit_Fetch_Stop::kOsmWayIdFieldNumber;
const int Transit_Fetch_Stop::kTimezoneFieldNumber;
const int Transit_Fetch_Stop::kWheelchairBoardingFieldNumber;
#endif  // !_MSC_VER

Transit_Fetch_Stop::Transit_Fetch_Stop()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void Transit_Fetch_Stop::InitAsDefaultInstance() {
}

Transit_Fetch_Stop::Transit_Fetch_Stop(const Transit_Fetch_Stop& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void Transit_Fetch_Stop::SharedCtor() {
  _cached_size_ = 0;
  lon_ = 0;
  lat_ = 0;
  graphid_ = GOOGLE_ULONGLONG(0);
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  onestop_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  osm_way_id_ = GOOGLE_ULONGLONG(0);
  timezone_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  wheelchair_boarding_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Transit_Fetch_Stop::~Transit_Fetch_Stop() {
  SharedDtor();
}

void Transit_Fetch_Stop::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (onestop_id_ != &::google::protobuf::internal::kEmptyString) {
    delete onestop_id_;
  }
  if (timezone_ != &::google::protobuf::internal::kEmptyString) {
    delete timezone_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void Transit_Fetch_Stop::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Transit_Fetch_Stop& Transit_Fetch_Stop::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_transit_5ffetch_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_transit_5ffetch_2eproto();
#endif
  return *default_instance_;
}

Transit_Fetch_Stop* Transit_Fetch_Stop::default_instance_ = NULL;

Transit_Fetch_Stop* Transit_Fetch_Stop::New() const {
  return new Transit_Fetch_Stop;
}

void Transit_Fetch_Stop::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    lon_ = 0;
    lat_ = 0;
    graphid_ = GOOGLE_ULONGLONG(0);
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    if (has_onestop_id()) {
      if (onestop_id_ != &::google::protobuf::internal::kEmptyString) {
        onestop_id_->clear();
      }
    }
    osm_way_id_ = GOOGLE_ULONGLONG(0);
    if (has_timezone()) {
      if (timezone_ != &::google::protobuf::internal::kEmptyString) {
        timezone_->clear();
      }
    }
    wheelchair_boarding_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool Transit_Fetch_Stop::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional float lon = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &lon_)));
          set_has_lon();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_lat;
        break;
      }

      // optional float lat = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_lat:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &lat_)));
          set_has_lat();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_graphid;
        break;
      }

      // optional uint64 graphid = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_graphid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &graphid_)));
          set_has_graphid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_name;
        break;
      }

      // optional string name = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_onestop_id;
        break;
      }

      // optional string onestop_id = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_onestop_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_onestop_id()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_osm_way_id;
        break;
      }

      // optional uint64 osm_way_id = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_osm_way_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &osm_way_id_)));
          set_has_osm_way_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(66)) goto parse_timezone;
        break;
      }

      // optional string timezone = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_timezone:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_timezone()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(72)) goto parse_wheelchair_boarding;
        break;
      }

      // optional bool wheelchair_boarding = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_wheelchair_boarding:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &wheelchair_boarding_)));
          set_has_wheelchair_boarding();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Transit_Fetch_Stop::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional float lon = 1;
  if (has_lon()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->lon(), output);
  }

  // optional float lat = 2;
  if (has_lat()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->lat(), output);
  }

  // optional uint64 graphid = 3;
  if (has_graphid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->graphid(), output);
  }

  // optional string name = 4;
  if (has_name()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->name(), output);
  }

  // optional string onestop_id = 5;
  if (has_onestop_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->onestop_id(), output);
  }

  // optional uint64 osm_way_id = 6;
  if (has_osm_way_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(6, this->osm_way_id(), output);
  }

  // optional string timezone = 8;
  if (has_timezone()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      8, this->timezone(), output);
  }

  // optional bool wheelchair_boarding = 9;
  if (has_wheelchair_boarding()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(9, this->wheelchair_boarding(), output);
  }

}

int Transit_Fetch_Stop::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional float lon = 1;
    if (has_lon()) {
      total_size += 1 + 4;
    }

    // optional float lat = 2;
    if (has_lat()) {
      total_size += 1 + 4;
    }

    // optional uint64 graphid = 3;
    if (has_graphid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->graphid());
    }

    // optional string name = 4;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional string onestop_id = 5;
    if (has_onestop_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->onestop_id());
    }

    // optional uint64 osm_way_id = 6;
    if (has_osm_way_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->osm_way_id());
    }

    // optional string timezone = 8;
    if (has_timezone()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->timezone());
    }

    // optional bool wheelchair_boarding = 9;
    if (has_wheelchair_boarding()) {
      total_size += 1 + 1;
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Transit_Fetch_Stop::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Transit_Fetch_Stop*>(&from));
}

void Transit_Fetch_Stop::MergeFrom(const Transit_Fetch_Stop& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_lon()) {
      set_lon(from.lon());
    }
    if (from.has_lat()) {
      set_lat(from.lat());
    }
    if (from.has_graphid()) {
      set_graphid(from.graphid());
    }
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_onestop_id()) {
      set_onestop_id(from.onestop_id());
    }
    if (from.has_osm_way_id()) {
      set_osm_way_id(from.osm_way_id());
    }
    if (from.has_timezone()) {
      set_timezone(from.timezone());
    }
    if (from.has_wheelchair_boarding()) {
      set_wheelchair_boarding(from.wheelchair_boarding());
    }
  }
}

void Transit_Fetch_Stop::CopyFrom(const Transit_Fetch_Stop& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Transit_Fetch_Stop::IsInitialized() const {

  return true;
}

void Transit_Fetch_Stop::Swap(Transit_Fetch_Stop* other) {
  if (other != this) {
    std::swap(lon_, other->lon_);
    std::swap(lat_, other->lat_);
    std::swap(graphid_, other->graphid_);
    std::swap(name_, other->name_);
    std::swap(onestop_id_, other->onestop_id_);
    std::swap(osm_way_id_, other->osm_way_id_);
    std::swap(timezone_, other->timezone_);
    std::swap(wheelchair_boarding_, other->wheelchair_boarding_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string Transit_Fetch_Stop::GetTypeName() const {
  return "valhalla.mjolnir.Transit_Fetch.Stop";
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Transit_Fetch_StopPair::kBikesAllowedFieldNumber;
const int Transit_Fetch_StopPair::kBlockIdFieldNumber;
const int Transit_Fetch_StopPair::kDestinationArrivalTimeFieldNumber;
const int Transit_Fetch_StopPair::kDestinationGraphidFieldNumber;
const int Transit_Fetch_StopPair::kDestinationOnestopIdFieldNumber;
const int Transit_Fetch_StopPair::kOperatedByOnestopIdFieldNumber;
const int Transit_Fetch_StopPair::kOriginDepartureTimeFieldNumber;
const int Transit_Fetch_StopPair::kOriginGraphidFieldNumber;
const int Transit_Fetch_StopPair::kOriginOnestopIdFieldNumber;
const int Transit_Fetch_StopPair::kRouteIndexFieldNumber;
const int Transit_Fetch_StopPair::kServiceAddedDatesFieldNumber;
const int Transit_Fetch_StopPair::kServiceDaysOfWeekFieldNumber;
const int Transit_Fetch_StopPair::kServiceEndDateFieldNumber;
const int Transit_Fetch_StopPair::kServiceExceptDatesFieldNumber;
const int Transit_Fetch_StopPair::kServiceStartDateFieldNumber;
const int Transit_Fetch_StopPair::kTripHeadsignFieldNumber;
const int Transit_Fetch_StopPair::kTripIdFieldNumber;
const int Transit_Fetch_StopPair::kWheelchairAccessibleFieldNumber;
const int Transit_Fetch_StopPair::kShapeIdFieldNumber;
const int Transit_Fetch_StopPair::kOriginDistTraveledFieldNumber;
const int Transit_Fetch_StopPair::kDestinationDistTraveledFieldNumber;
const int Transit_Fetch_StopPair::kFrequencyEndTimeFieldNumber;
const int Transit_Fetch_StopPair::kFrequencyHeadwaySecondsFieldNumber;
#endif  // !_MSC_VER

Transit_Fetch_StopPair::Transit_Fetch_StopPair()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void Transit_Fetch_StopPair::InitAsDefaultInstance() {
}

Transit_Fetch_StopPair::Transit_Fetch_StopPair(const Transit_Fetch_StopPair& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void Transit_Fetch_StopPair::SharedCtor() {
  _cached_size_ = 0;
  bikes_allowed_ = false;
  block_id_ = 0u;
  destination_arrival_time_ = 0u;
  destination_graphid_ = GOOGLE_ULONGLONG(0);
  destination_onestop_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  operated_by_onestop_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  origin_departure_time_ = 0u;
  origin_graphid_ = GOOGLE_ULONGLONG(0);
  origin_onestop_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  route_index_ = 0u;
  service_end_date_ = 0u;
  service_start_date_ = 0u;
  trip_headsign_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  trip_id_ = 0u;
  wheelchair_accessible_ = false;
  shape_id_ = 0u;
  origin_dist_traveled_ = 0;
  destination_dist_traveled_ = 0;
  frequency_end_time_ = 0u;
  frequency_headway_seconds_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Transit_Fetch_StopPair::~Transit_Fetch_StopPair() {
  SharedDtor();
}

void Transit_Fetch_StopPair::SharedDtor() {
  if (destination_onestop_id_ != &::google::protobuf::internal::kEmptyString) {
    delete destination_onestop_id_;
  }
  if (operated_by_onestop_id_ != &::google::protobuf::internal::kEmptyString) {
    delete operated_by_onestop_id_;
  }
  if (origin_onestop_id_ != &::google::protobuf::internal::kEmptyString) {
    delete origin_onestop_id_;
  }
  if (trip_headsign_ != &::google::protobuf::internal::kEmptyString) {
    delete trip_headsign_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void Transit_Fetch_StopPair::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Transit_Fetch_StopPair& Transit_Fetch_StopPair::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_transit_5ffetch_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_transit_5ffetch_2eproto();
#endif
  return *default_instance_;
}

Transit_Fetch_StopPair* Transit_Fetch_StopPair::default_instance_ = NULL;

Transit_Fetch_StopPair* Transit_Fetch_StopPair::New() const {
  return new Transit_Fetch_StopPair;
}

void Transit_Fetch_StopPair::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    bikes_allowed_ = false;
    block_id_ = 0u;
    destination_arrival_time_ = 0u;
    destination_graphid_ = GOOGLE_ULONGLONG(0);
    if (has_destination_onestop_id()) {
      if (destination_onestop_id_ != &::google::protobuf::internal::kEmptyString) {
        destination_onestop_id_->clear();
      }
    }
    if (has_operated_by_onestop_id()) {
      if (operated_by_onestop_id_ != &::google::protobuf::internal::kEmptyString) {
        operated_by_onestop_id_->clear();
      }
    }
    origin_departure_time_ = 0u;
    origin_graphid_ = GOOGLE_ULONGLONG(0);
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (has_origin_onestop_id()) {
      if (origin_onestop_id_ != &::google::protobuf::internal::kEmptyString) {
        origin_onestop_id_->clear();
      }
    }
    route_index_ = 0u;
    service_end_date_ = 0u;
    service_start_date_ = 0u;
    if (has_trip_headsign()) {
      if (trip_headsign_ != &::google::protobuf::internal::kEmptyString) {
        trip_headsign_->clear();
      }
    }
  }
  if (_has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    trip_id_ = 0u;
    wheelchair_accessible_ = false;
    shape_id_ = 0u;
    origin_dist_traveled_ = 0;
    destination_dist_traveled_ = 0;
    frequency_end_time_ = 0u;
    frequency_headway_seconds_ = 0u;
  }
  service_added_dates_.Clear();
  service_days_of_week_.Clear();
  service_except_dates_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool Transit_Fetch_StopPair::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool bikes_allowed = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &bikes_allowed_)));
          set_has_bikes_allowed();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_block_id;
        break;
      }

      // optional uint32 block_id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_block_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &block_id_)));
          set_has_block_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_destination_arrival_time;
        break;
      }

      // optional uint32 destination_arrival_time = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_destination_arrival_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &destination_arrival_time_)));
          set_has_destination_arrival_time();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_destination_graphid;
        break;
      }

      // optional uint64 destination_graphid = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_destination_graphid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &destination_graphid_)));
          set_has_destination_graphid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_destination_onestop_id;
        break;
      }

      // optional string destination_onestop_id = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_destination_onestop_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_destination_onestop_id()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_operated_by_onestop_id;
        break;
      }

      // optional string operated_by_onestop_id = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_operated_by_onestop_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_operated_by_onestop_id()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_origin_departure_time;
        break;
      }

      // optional uint32 origin_departure_time = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_origin_departure_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &origin_departure_time_)));
          set_has_origin_departure_time();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_origin_graphid;
        break;
      }

      // optional uint64 origin_graphid = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_origin_graphid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &origin_graphid_)));
          set_has_origin_graphid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(74)) goto parse_origin_onestop_id;
        break;
      }

      // optional string origin_onestop_id = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_origin_onestop_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_origin_onestop_id()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(80)) goto parse_route_index;
        break;
      }

      // optional uint32 route_index = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_route_index:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &route_index_)));
          set_has_route_index();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(88)) goto parse_service_added_dates;
        break;
      }

      // repeated uint32 service_added_dates = 11;
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_service_added_dates:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 88, input, this->mutable_service_added_dates())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_service_added_dates())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(88)) goto parse_service_added_dates;
        if (input->ExpectTag(96)) goto parse_service_days_of_week;
        break;
      }

      // repeated bool service_days_of_week = 12;
      case 12: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_service_days_of_week:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 1, 96, input, this->mutable_service_days_of_week())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, this->mutable_service_days_of_week())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(96)) goto parse_service_days_of_week;
        if (input->ExpectTag(104)) goto parse_service_end_date;
        break;
      }

      // optional uint32 service_end_date = 13;
      case 13: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_service_end_date:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &service_end_date_)));
          set_has_service_end_date();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(112)) goto parse_service_except_dates;
        break;
      }

      // repeated uint32 service_except_dates = 14;
      case 14: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_service_except_dates:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 112, input, this->mutable_service_except_dates())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_service_except_dates())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(112)) goto parse_service_except_dates;
        if (input->ExpectTag(120)) goto parse_service_start_date;
        break;
      }

      // optional uint32 service_start_date = 15;
      case 15: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_service_start_date:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &service_start_date_)));
          set_has_service_start_date();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(130)) goto parse_trip_headsign;
        break;
      }

      // optional string trip_headsign = 16;
      case 16: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_trip_headsign:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_trip_headsign()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(136)) goto parse_trip_id;
        break;
      }

      // optional uint32 trip_id = 17;
      case 17: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_trip_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &trip_id_)));
          set_has_trip_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(144)) goto parse_wheelchair_accessible;
        break;
      }

      // optional bool wheelchair_accessible = 18;
      case 18: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_wheelchair_accessible:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &wheelchair_accessible_)));
          set_has_wheelchair_accessible();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(160)) goto parse_shape_id;
        break;
      }

      // optional uint32 shape_id = 20;
      case 20: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_shape_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &shape_id_)));
          set_has_shape_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(173)) goto parse_origin_dist_traveled;
        break;
      }

      // optional float origin_dist_traveled = 21;
      case 21: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_origin_dist_traveled:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &origin_dist_traveled_)));
          set_has_origin_dist_traveled();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(181)) goto parse_destination_dist_traveled;
        break;
      }

      // optional float destination_dist_traveled = 22;
      case 22: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_destination_dist_traveled:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &destination_dist_traveled_)));
          set_has_destination_dist_traveled();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(184)) goto parse_frequency_end_time;
        break;
      }

      // optional uint32 frequency_end_time = 23;
      case 23: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_frequency_end_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &frequency_end_time_)));
          set_has_frequency_end_time();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(192)) goto parse_frequency_headway_seconds;
        break;
      }

      // optional uint32 frequency_headway_seconds = 24;
      case 24: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_frequency_headway_seconds:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &frequency_headway_seconds_)));
          set_has_frequency_headway_seconds();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Transit_Fetch_StopPair::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bool bikes_allowed = 1;
  if (has_bikes_allowed()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->bikes_allowed(), output);
  }

  // optional uint32 block_id = 2;
  if (has_block_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->block_id(), output);
  }

  // optional uint32 destination_arrival_time = 3;
  if (has_destination_arrival_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->destination_arrival_time(), output);
  }

  // optional uint64 destination_graphid = 4;
  if (has_destination_graphid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(4, this->destination_graphid(), output);
  }

  // optional string destination_onestop_id = 5;
  if (has_destination_onestop_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->destination_onestop_id(), output);
  }

  // optional string operated_by_onestop_id = 6;
  if (has_operated_by_onestop_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->operated_by_onestop_id(), output);
  }

  // optional uint32 origin_departure_time = 7;
  if (has_origin_departure_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->origin_departure_time(), output);
  }

  // optional uint64 origin_graphid = 8;
  if (has_origin_graphid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(8, this->origin_graphid(), output);
  }

  // optional string origin_onestop_id = 9;
  if (has_origin_onestop_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      9, this->origin_onestop_id(), output);
  }

  // optional uint32 route_index = 10;
  if (has_route_index()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(10, this->route_index(), output);
  }

  // repeated uint32 service_added_dates = 11;
  for (int i = 0; i < this->service_added_dates_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(
      11, this->service_added_dates(i), output);
  }

  // repeated bool service_days_of_week = 12;
  for (int i = 0; i < this->service_days_of_week_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(
      12, this->service_days_of_week(i), output);
  }

  // optional uint32 service_end_date = 13;
  if (has_service_end_date()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(13, this->service_end_date(), output);
  }

  // repeated uint32 service_except_dates = 14;
  for (int i = 0; i < this->service_except_dates_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(
      14, this->service_except_dates(i), output);
  }

  // optional uint32 service_start_date = 15;
  if (has_service_start_date()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(15, this->service_start_date(), output);
  }

  // optional string trip_headsign = 16;
  if (has_trip_headsign()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      16, this->trip_headsign(), output);
  }

  // optional uint32 trip_id = 17;
  if (has_trip_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(17, this->trip_id(), output);
  }

  // optional bool wheelchair_accessible = 18;
  if (has_wheelchair_accessible()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(18, this->wheelchair_accessible(), output);
  }

  // optional uint32 shape_id = 20;
  if (has_shape_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(20, this->shape_id(), output);
  }

  // optional float origin_dist_traveled = 21;
  if (has_origin_dist_traveled()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(21, this->origin_dist_traveled(), output);
  }

  // optional float destination_dist_traveled = 22;
  if (has_destination_dist_traveled()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(22, this->destination_dist_traveled(), output);
  }

  // optional uint32 frequency_end_time = 23;
  if (has_frequency_end_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(23, this->frequency_end_time(), output);
  }

  // optional uint32 frequency_headway_seconds = 24;
  if (has_frequency_headway_seconds()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(24, this->frequency_headway_seconds(), output);
  }

}

int Transit_Fetch_StopPair::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bool bikes_allowed = 1;
    if (has_bikes_allowed()) {
      total_size += 1 + 1;
    }

    // optional uint32 block_id = 2;
    if (has_block_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->block_id());
    }

    // optional uint32 destination_arrival_time = 3;
    if (has_destination_arrival_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->destination_arrival_time());
    }

    // optional uint64 destination_graphid = 4;
    if (has_destination_graphid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->destination_graphid());
    }

    // optional string destination_onestop_id = 5;
    if (has_destination_onestop_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->destination_onestop_id());
    }

    // optional string operated_by_onestop_id = 6;
    if (has_operated_by_onestop_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->operated_by_onestop_id());
    }

    // optional uint32 origin_departure_time = 7;
    if (has_origin_departure_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->origin_departure_time());
    }

    // optional uint64 origin_graphid = 8;
    if (has_origin_graphid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->origin_graphid());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional string origin_onestop_id = 9;
    if (has_origin_onestop_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->origin_onestop_id());
    }

    // optional uint32 route_index = 10;
    if (has_route_index()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->route_index());
    }

    // optional uint32 service_end_date = 13;
    if (has_service_end_date()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->service_end_date());
    }

    // optional uint32 service_start_date = 15;
    if (has_service_start_date()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->service_start_date());
    }

    // optional string trip_headsign = 16;
    if (has_trip_headsign()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->trip_headsign());
    }

  }
  if (_has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    // optional uint32 trip_id = 17;
    if (has_trip_id()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->trip_id());
    }

    // optional bool wheelchair_accessible = 18;
    if (has_wheelchair_accessible()) {
      total_size += 2 + 1;
    }

    // optional uint32 shape_id = 20;
    if (has_shape_id()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->shape_id());
    }

    // optional float origin_dist_traveled = 21;
    if (has_origin_dist_traveled()) {
      total_size += 2 + 4;
    }

    // optional float destination_dist_traveled = 22;
    if (has_destination_dist_traveled()) {
      total_size += 2 + 4;
    }

    // optional uint32 frequency_end_time = 23;
    if (has_frequency_end_time()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->frequency_end_time());
    }

    // optional uint32 frequency_headway_seconds = 24;
    if (has_frequency_headway_seconds()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->frequency_headway_seconds());
    }

  }
  // repeated uint32 service_added_dates = 11;
  {
    int data_size = 0;
    for (int i = 0; i < this->service_added_dates_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->service_added_dates(i));
    }
    total_size += 1 * this->service_added_dates_size() + data_size;
  }

  // repeated bool service_days_of_week = 12;
  {
    int data_size = 0;
    data_size = 1 * this->service_days_of_week_size();
    total_size += 1 * this->service_days_of_week_size() + data_size;
  }

  // repeated uint32 service_except_dates = 14;
  {
    int data_size = 0;
    for (int i = 0; i < this->service_except_dates_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->service_except_dates(i));
    }
    total_size += 1 * this->service_except_dates_size() + data_size;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Transit_Fetch_StopPair::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Transit_Fetch_StopPair*>(&from));
}

void Transit_Fetch_StopPair::MergeFrom(const Transit_Fetch_StopPair& from) {
  GOOGLE_CHECK_NE(&from, this);
  service_added_dates_.MergeFrom(from.service_added_dates_);
  service_days_of_week_.MergeFrom(from.service_days_of_week_);
  service_except_dates_.MergeFrom(from.service_except_dates_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_bikes_allowed()) {
      set_bikes_allowed(from.bikes_allowed());
    }
    if (from.has_block_id()) {
      set_block_id(from.block_id());
    }
    if (from.has_destination_arrival_time()) {
      set_destination_arrival_time(from.destination_arrival_time());
    }
    if (from.has_destination_graphid()) {
      set_destination_graphid(from.destination_graphid());
    }
    if (from.has_destination_onestop_id()) {
      set_destination_onestop_id(from.destination_onestop_id());
    }
    if (from.has_operated_by_onestop_id()) {
      set_operated_by_onestop_id(from.operated_by_onestop_id());
    }
    if (from.has_origin_departure_time()) {
      set_origin_departure_time(from.origin_departure_time());
    }
    if (from.has_origin_graphid()) {
      set_origin_graphid(from.origin_graphid());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_origin_onestop_id()) {
      set_origin_onestop_id(from.origin_onestop_id());
    }
    if (from.has_route_index()) {
      set_route_index(from.route_index());
    }
    if (from.has_service_end_date()) {
      set_service_end_date(from.service_end_date());
    }
    if (from.has_service_start_date()) {
      set_service_start_date(from.service_start_date());
    }
    if (from.has_trip_headsign()) {
      set_trip_headsign(from.trip_headsign());
    }
  }
  if (from._has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    if (from.has_trip_id()) {
      set_trip_id(from.trip_id());
    }
    if (from.has_wheelchair_accessible()) {
      set_wheelchair_accessible(from.wheelchair_accessible());
    }
    if (from.has_shape_id()) {
      set_shape_id(from.shape_id());
    }
    if (from.has_origin_dist_traveled()) {
      set_origin_dist_traveled(from.origin_dist_traveled());
    }
    if (from.has_destination_dist_traveled()) {
      set_destination_dist_traveled(from.destination_dist_traveled());
    }
    if (from.has_frequency_end_time()) {
      set_frequency_end_time(from.frequency_end_time());
    }
    if (from.has_frequency_headway_seconds()) {
      set_frequency_headway_seconds(from.frequency_headway_seconds());
    }
  }
}

void Transit_Fetch_StopPair::CopyFrom(const Transit_Fetch_StopPair& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Transit_Fetch_StopPair::IsInitialized() const {

  return true;
}

void Transit_Fetch_StopPair::Swap(Transit_Fetch_StopPair* other) {
  if (other != this) {
    std::swap(bikes_allowed_, other->bikes_allowed_);
    std::swap(block_id_, other->block_id_);
    std::swap(destination_arrival_time_, other->destination_arrival_time_);
    std::swap(destination_graphid_, other->destination_graphid_);
    std::swap(destination_onestop_id_, other->destination_onestop_id_);
    std::swap(operated_by_onestop_id_, other->operated_by_onestop_id_);
    std::swap(origin_departure_time_, other->origin_departure_time_);
    std::swap(origin_graphid_, other->origin_graphid_);
    std::swap(origin_onestop_id_, other->origin_onestop_id_);
    std::swap(route_index_, other->route_index_);
    service_added_dates_.Swap(&other->service_added_dates_);
    service_days_of_week_.Swap(&other->service_days_of_week_);
    std::swap(service_end_date_, other->service_end_date_);
    service_except_dates_.Swap(&other->service_except_dates_);
    std::swap(service_start_date_, other->service_start_date_);
    std::swap(trip_headsign_, other->trip_headsign_);
    std::swap(trip_id_, other->trip_id_);
    std::swap(wheelchair_accessible_, other->wheelchair_accessible_);
    std::swap(shape_id_, other->shape_id_);
    std::swap(origin_dist_traveled_, other->origin_dist_traveled_);
    std::swap(destination_dist_traveled_, other->destination_dist_traveled_);
    std::swap(frequency_end_time_, other->frequency_end_time_);
    std::swap(frequency_headway_seconds_, other->frequency_headway_seconds_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string Transit_Fetch_StopPair::GetTypeName() const {
  return "valhalla.mjolnir.Transit_Fetch.StopPair";
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Transit_Fetch_Route::kNameFieldNumber;
const int Transit_Fetch_Route::kOnestopIdFieldNumber;
const int Transit_Fetch_Route::kOperatedByNameFieldNumber;
const int Transit_Fetch_Route::kOperatedByOnestopIdFieldNumber;
const int Transit_Fetch_Route::kOperatedByWebsiteFieldNumber;
const int Transit_Fetch_Route::kRouteColorFieldNumber;
const int Transit_Fetch_Route::kRouteDescFieldNumber;
const int Transit_Fetch_Route::kRouteLongNameFieldNumber;
const int Transit_Fetch_Route::kRouteTextColorFieldNumber;
const int Transit_Fetch_Route::kVehicleTypeFieldNumber;
#endif  // !_MSC_VER

Transit_Fetch_Route::Transit_Fetch_Route()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void Transit_Fetch_Route::InitAsDefaultInstance() {
}

Transit_Fetch_Route::Transit_Fetch_Route(const Transit_Fetch_Route& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void Transit_Fetch_Route::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  onestop_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  operated_by_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  operated_by_onestop_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  operated_by_website_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  route_color_ = 0u;
  route_desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  route_long_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  route_text_color_ = 0u;
  vehicle_type_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Transit_Fetch_Route::~Transit_Fetch_Route() {
  SharedDtor();
}

void Transit_Fetch_Route::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (onestop_id_ != &::google::protobuf::internal::kEmptyString) {
    delete onestop_id_;
  }
  if (operated_by_name_ != &::google::protobuf::internal::kEmptyString) {
    delete operated_by_name_;
  }
  if (operated_by_onestop_id_ != &::google::protobuf::internal::kEmptyString) {
    delete operated_by_onestop_id_;
  }
  if (operated_by_website_ != &::google::protobuf::internal::kEmptyString) {
    delete operated_by_website_;
  }
  if (route_desc_ != &::google::protobuf::internal::kEmptyString) {
    delete route_desc_;
  }
  if (route_long_name_ != &::google::protobuf::internal::kEmptyString) {
    delete route_long_name_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void Transit_Fetch_Route::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Transit_Fetch_Route& Transit_Fetch_Route::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_transit_5ffetch_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_transit_5ffetch_2eproto();
#endif
  return *default_instance_;
}

Transit_Fetch_Route* Transit_Fetch_Route::default_instance_ = NULL;

Transit_Fetch_Route* Transit_Fetch_Route::New() const {
  return new Transit_Fetch_Route;
}

void Transit_Fetch_Route::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    if (has_onestop_id()) {
      if (onestop_id_ != &::google::protobuf::internal::kEmptyString) {
        onestop_id_->clear();
      }
    }
    if (has_operated_by_name()) {
      if (operated_by_name_ != &::google::protobuf::internal::kEmptyString) {
        operated_by_name_->clear();
      }
    }
    if (has_operated_by_onestop_id()) {
      if (operated_by_onestop_id_ != &::google::protobuf::internal::kEmptyString) {
        operated_by_onestop_id_->clear();
      }
    }
    if (has_operated_by_website()) {
      if (operated_by_website_ != &::google::protobuf::internal::kEmptyString) {
        operated_by_website_->clear();
      }
    }
    route_color_ = 0u;
    if (has_route_desc()) {
      if (route_desc_ != &::google::protobuf::internal::kEmptyString) {
        route_desc_->clear();
      }
    }
    if (has_route_long_name()) {
      if (route_long_name_ != &::google::protobuf::internal::kEmptyString) {
        route_long_name_->clear();
      }
    }
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    route_text_color_ = 0u;
    vehicle_type_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool Transit_Fetch_Route::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_onestop_id;
        break;
      }

      // optional string onestop_id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_onestop_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_onestop_id()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_operated_by_name;
        break;
      }

      // optional string operated_by_name = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_operated_by_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_operated_by_name()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_operated_by_onestop_id;
        break;
      }

      // optional string operated_by_onestop_id = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_operated_by_onestop_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_operated_by_onestop_id()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_operated_by_website;
        break;
      }

      // optional string operated_by_website = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_operated_by_website:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_operated_by_website()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_route_color;
        break;
      }

      // optional uint32 route_color = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_route_color:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &route_color_)));
          set_has_route_color();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(58)) goto parse_route_desc;
        break;
      }

      // optional string route_desc = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_route_desc:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_route_desc()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(66)) goto parse_route_long_name;
        break;
      }

      // optional string route_long_name = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_route_long_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_route_long_name()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(72)) goto parse_route_text_color;
        break;
      }

      // optional uint32 route_text_color = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_route_text_color:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &route_text_color_)));
          set_has_route_text_color();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(80)) goto parse_vehicle_type;
        break;
      }

      // optional .valhalla.mjolnir.Transit_Fetch.VehicleType vehicle_type = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_vehicle_type:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::valhalla::mjolnir::Transit_Fetch_VehicleType_IsValid(value)) {
            set_vehicle_type(static_cast< ::valhalla::mjolnir::Transit_Fetch_VehicleType >(value));
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Transit_Fetch_Route::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }

  // optional string onestop_id = 2;
  if (has_onestop_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->onestop_id(), output);
  }

  // optional string operated_by_name = 3;
  if (has_operated_by_name()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->operated_by_name(), output);
  }

  // optional string operated_by_onestop_id = 4;
  if (has_operated_by_onestop_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->operated_by_onestop_id(), output);
  }

  // optional string operated_by_website = 5;
  if (has_operated_by_website()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->operated_by_website(), output);
  }

  // optional uint32 route_color = 6;
  if (has_route_color()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->route_color(), output);
  }

  // optional string route_desc = 7;
  if (has_route_desc()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      7, this->route_desc(), output);
  }

  // optional string route_long_name = 8;
  if (has_route_long_name()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      8, this->route_long_name(), output);
  }

  // optional uint32 route_text_color = 9;
  if (has_route_text_color()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(9, this->route_text_color(), output);
  }

  // optional .valhalla.mjolnir.Transit_Fetch.VehicleType vehicle_type = 10;
  if (has_vehicle_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      10, this->vehicle_type(), output);
  }

}

int Transit_Fetch_Route::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional string onestop_id = 2;
    if (has_onestop_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->onestop_id());
    }

    // optional string operated_by_name = 3;
    if (has_operated_by_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->operated_by_name());
    }

    // optional string operated_by_onestop_id = 4;
    if (has_operated_by_onestop_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->operated_by_onestop_id());
    }

    // optional string operated_by_website = 5;
    if (has_operated_by_website()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->operated_by_website());
    }

    // optional uint32 route_color = 6;
    if (has_route_color()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->route_color());
    }

    // optional string route_desc = 7;
    if (has_route_desc()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->route_desc());
    }

    // optional string route_long_name = 8;
    if (has_route_long_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->route_long_name());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional uint32 route_text_color = 9;
    if (has_route_text_color()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->route_text_color());
    }

    // optional .valhalla.mjolnir.Transit_Fetch.VehicleType vehicle_type = 10;
    if (has_vehicle_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->vehicle_type());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Transit_Fetch_Route::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Transit_Fetch_Route*>(&from));
}

void Transit_Fetch_Route::MergeFrom(const Transit_Fetch_Route& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_onestop_id()) {
      set_onestop_id(from.onestop_id());
    }
    if (from.has_operated_by_name()) {
      set_operated_by_name(from.operated_by_name());
    }
    if (from.has_operated_by_onestop_id()) {
      set_operated_by_onestop_id(from.operated_by_onestop_id());
    }
    if (from.has_operated_by_website()) {
      set_operated_by_website(from.operated_by_website());
    }
    if (from.has_route_color()) {
      set_route_color(from.route_color());
    }
    if (from.has_route_desc()) {
      set_route_desc(from.route_desc());
    }
    if (from.has_route_long_name()) {
      set_route_long_name(from.route_long_name());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_route_text_color()) {
      set_route_text_color(from.route_text_color());
    }
    if (from.has_vehicle_type()) {
      set_vehicle_type(from.vehicle_type());
    }
  }
}

void Transit_Fetch_Route::CopyFrom(const Transit_Fetch_Route& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Transit_Fetch_Route::IsInitialized() const {

  return true;
}

void Transit_Fetch_Route::Swap(Transit_Fetch_Route* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(onestop_id_, other->onestop_id_);
    std::swap(operated_by_name_, other->operated_by_name_);
    std::swap(operated_by_onestop_id_, other->operated_by_onestop_id_);
    std::swap(operated_by_website_, other->operated_by_website_);
    std::swap(route_color_, other->route_color_);
    std::swap(route_desc_, other->route_desc_);
    std::swap(route_long_name_, other->route_long_name_);
    std::swap(route_text_color_, other->route_text_color_);
    std::swap(vehicle_type_, other->vehicle_type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string Transit_Fetch_Route::GetTypeName() const {
  return "valhalla.mjolnir.Transit_Fetch.Route";
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Transit_Fetch_Shape::kShapeIdFieldNumber;
const int Transit_Fetch_Shape::kEncodedShapeFieldNumber;
#endif  // !_MSC_VER

Transit_Fetch_Shape::Transit_Fetch_Shape()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void Transit_Fetch_Shape::InitAsDefaultInstance() {
}

Transit_Fetch_Shape::Transit_Fetch_Shape(const Transit_Fetch_Shape& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void Transit_Fetch_Shape::SharedCtor() {
  _cached_size_ = 0;
  shape_id_ = 0u;
  encoded_shape_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Transit_Fetch_Shape::~Transit_Fetch_Shape() {
  SharedDtor();
}

void Transit_Fetch_Shape::SharedDtor() {
  if (encoded_shape_ != &::google::protobuf::internal::kEmptyString) {
    delete encoded_shape_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void Transit_Fetch_Shape::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Transit_Fetch_Shape& Transit_Fetch_Shape::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_transit_5ffetch_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_transit_5ffetch_2eproto();
#endif
  return *default_instance_;
}

Transit_Fetch_Shape* Transit_Fetch_Shape::default_instance_ = NULL;

Transit_Fetch_Shape* Transit_Fetch_Shape::New() const {
  return new Transit_Fetch_Shape;
}

void Transit_Fetch_Shape::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    shape_id_ = 0u;
    if (has_encoded_shape()) {
      if (encoded_shape_ != &::google::protobuf::internal::kEmptyString) {
        encoded_shape_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool Transit_Fetch_Shape::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 shape_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &shape_id_)));
          set_has_shape_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_encoded_shape;
        break;
      }

      // optional bytes encoded_shape = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_encoded_shape:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_encoded_shape()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Transit_Fetch_Shape::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional uint32 shape_id = 1;
  if (has_shape_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->shape_id(), output);
  }

  // optional bytes encoded_shape = 2;
  if (has_encoded_shape()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->encoded_shape(), output);
  }

}

int Transit_Fetch_Shape::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 shape_id = 1;
    if (has_shape_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->shape_id());
    }

    // optional bytes encoded_shape = 2;
    if (has_encoded_shape()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->encoded_shape());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Transit_Fetch_Shape::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Transit_Fetch_Shape*>(&from));
}

void Transit_Fetch_Shape::MergeFrom(const Transit_Fetch_Shape& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_shape_id()) {
      set_shape_id(from.shape_id());
    }
    if (from.has_encoded_shape()) {
      set_encoded_shape(from.encoded_shape());
    }
  }
}

void Transit_Fetch_Shape::CopyFrom(const Transit_Fetch_Shape& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Transit_Fetch_Shape::IsInitialized() const {

  return true;
}

void Transit_Fetch_Shape::Swap(Transit_Fetch_Shape* other) {
  if (other != this) {
    std::swap(shape_id_, other->shape_id_);
    std::swap(encoded_shape_, other->encoded_shape_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string Transit_Fetch_Shape::GetTypeName() const {
  return "valhalla.mjolnir.Transit_Fetch.Shape";
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Transit_Fetch::kStopsFieldNumber;
const int Transit_Fetch::kStopPairsFieldNumber;
const int Transit_Fetch::kRoutesFieldNumber;
const int Transit_Fetch::kShapesFieldNumber;
#endif  // !_MSC_VER

Transit_Fetch::Transit_Fetch()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void Transit_Fetch::InitAsDefaultInstance() {
}

Transit_Fetch::Transit_Fetch(const Transit_Fetch& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void Transit_Fetch::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Transit_Fetch::~Transit_Fetch() {
  SharedDtor();
}

void Transit_Fetch::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void Transit_Fetch::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Transit_Fetch& Transit_Fetch::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_transit_5ffetch_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_transit_5ffetch_2eproto();
#endif
  return *default_instance_;
}

Transit_Fetch* Transit_Fetch::default_instance_ = NULL;

Transit_Fetch* Transit_Fetch::New() const {
  return new Transit_Fetch;
}

void Transit_Fetch::Clear() {
  stops_.Clear();
  stop_pairs_.Clear();
  routes_.Clear();
  shapes_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool Transit_Fetch::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .valhalla.mjolnir.Transit_Fetch.Stop stops = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_stops:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_stops()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_stops;
        if (input->ExpectTag(18)) goto parse_stop_pairs;
        break;
      }

      // repeated .valhalla.mjolnir.Transit_Fetch.StopPair stop_pairs = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_stop_pairs:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_stop_pairs()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_stop_pairs;
        if (input->ExpectTag(26)) goto parse_routes;
        break;
      }

      // repeated .valhalla.mjolnir.Transit_Fetch.Route routes = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_routes:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_routes()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_routes;
        if (input->ExpectTag(34)) goto parse_shapes;
        break;
      }

      // repeated .valhalla.mjolnir.Transit_Fetch.Shape shapes = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_shapes:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_shapes()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_shapes;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Transit_Fetch::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .valhalla.mjolnir.Transit_Fetch.Stop stops = 1;
  for (int i = 0; i < this->stops_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->stops(i), output);
  }

  // repeated .valhalla.mjolnir.Transit_Fetch.StopPair stop_pairs = 2;
  for (int i = 0; i < this->stop_pairs_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, this->stop_pairs(i), output);
  }

  // repeated .valhalla.mjolnir.Transit_Fetch.Route routes = 3;
  for (int i = 0; i < this->routes_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, this->routes(i), output);
  }

  // repeated .valhalla.mjolnir.Transit_Fetch.Shape shapes = 4;
  for (int i = 0; i < this->shapes_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      4, this->shapes(i), output);
  }

}

int Transit_Fetch::ByteSize() const {
  int total_size = 0;

  // repeated .valhalla.mjolnir.Transit_Fetch.Stop stops = 1;
  total_size += 1 * this->stops_size();
  for (int i = 0; i < this->stops_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->stops(i));
  }

  // repeated .valhalla.mjolnir.Transit_Fetch.StopPair stop_pairs = 2;
  total_size += 1 * this->stop_pairs_size();
  for (int i = 0; i < this->stop_pairs_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->stop_pairs(i));
  }

  // repeated .valhalla.mjolnir.Transit_Fetch.Route routes = 3;
  total_size += 1 * this->routes_size();
  for (int i = 0; i < this->routes_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->routes(i));
  }

  // repeated .valhalla.mjolnir.Transit_Fetch.Shape shapes = 4;
  total_size += 1 * this->shapes_size();
  for (int i = 0; i < this->shapes_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->shapes(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Transit_Fetch::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Transit_Fetch*>(&from));
}

void Transit_Fetch::MergeFrom(const Transit_Fetch& from) {
  GOOGLE_CHECK_NE(&from, this);
  stops_.MergeFrom(from.stops_);
  stop_pairs_.MergeFrom(from.stop_pairs_);
  routes_.MergeFrom(from.routes_);
  shapes_.MergeFrom(from.shapes_);
}

void Transit_Fetch::CopyFrom(const Transit_Fetch& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Transit_Fetch::IsInitialized() const {

  return true;
}

void Transit_Fetch::Swap(Transit_Fetch* other) {
  if (other != this) {
    stops_.Swap(&other->stops_);
    stop_pairs_.Swap(&other->stop_pairs_);
    routes_.Swap(&other->routes_);
    shapes_.Swap(&other->shapes_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string Transit_Fetch::GetTypeName() const {
  return "valhalla.mjolnir.Transit_Fetch";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace mjolnir
}  // namespace valhalla

// @@protoc_insertion_point(global_scope)
